class NavigationLocators:
    MAIN = "//ul[@id='menu-primary-menu']//a[contains(text(), 'Главная')]"
    MENU = "//ul[@id='menu-primary-menu']//a[contains(text(), 'Меню')]"
    DELIVERY_AND_PAYMENT = "//ul[@id='menu-primary-menu']//a[contains(text(), 'Доставка и оплата')]"
    STOCK = "//ul[@id='menu-primary-menu']//a[contains(text(), 'Акции')]"
    ABOUT_US = "//ul[@id='menu-primary-menu']//a[contains(text(), 'О нас')]"
    CART = "//ul[@id='menu-primary-menu']//a[contains(text(), 'Корзина')]"
    MY_ACCOUNT = "//ul[@id='menu-primary-menu']//a[contains(text(), 'Мой аккаунт')]"
    ORDERING = "//ul[@id='menu-primary-menu']//a[contains(text(), 'Оформление заказа')]"
    BONUS = "//ul[@id='menu-primary-menu']//a[contains(text(), 'Бонусная программа')]"
    SECTIONS = "//div/h2"
    PAGE_TITLE = "//div[@class='ak-container']/h1"
    SUBTITLE = "//div[@id='accesspress-breadcrumb']/span"
    SUBMENU_PIZZA = "//ul[@class='sub-menu']/li/a[contains(text(), 'Пицца')]"
    SUBMENU_DESSERTS = "//ul[@class='sub-menu']/li/a[contains(text(), 'Десерты')]"
    SUBMENU_DRINKS = "//ul[@class='sub-menu']/li/a[contains(text(), 'Напитки')]"
